### ISSUE TITLE
Inconsistent naming scheme

### ISSUE THREAD

**Issue by supertopher** [concourse/pool-resource#12]
Claimed/unclaimed is called everywhere except when you are `releasing` a lock.  

The readme talks alot about claiming and unclaiming locks, yet the command for unclaiming a lock is not `unclaim` it is `release`  In conversation with my pair this had made explaining how to use the lock resource unclear.  Two different pairs have shown confusion over the lack on an `unclaim` command.

Furthermore we use the word release to describe, BOSH releases and github releases.  It is confusing when i say "Hay bosh just cut a new release is the lock released?"  T

Thanks for reading this, we understand if you do not wish to followthrough, just some feedback :heart:

**Comment by vito** [comment]
We chatted in Slack about this a while back; I don't really think there's anything to do here.
