### ISSUE TITLE
Claiming too quickly after an unclaim causes 'error: lock instance is no longer acquired'

### ISSUE THREAD

**Issue by pivotal-topher-bullock** [concourse/pool-resource#2]
We have two jobs which try to acquire a lock on the same pool ( with only one lock to acquire ), the first one to acquire the lock failed to release the lock because the second claimed the env immediately after the unclaim commit. [Probably related to this check](https://github.com/concourse/pool-resource/blob/0d49c16b632cf47d27a1c81e33702a8c30a8888f/assets/in#L17)

**Job 1**

 :arrow_up: Env
  ```
  acquiring lock on: aws-bosh-release
  ```

  :arrow_down: Env
  ```
  Cloning into '/tmp/build/get'...
  9f3afaf claiming: mars
  ```

**bunch of jobs and stuff**

:arrow_up: Env
``` 
releasing lock: mars on pool: aws-bosh-release 
```

 :arrow_down: Env
  ```
  Cloning into '/tmp/build/get'...
  f1169b2 unclaiming: mars
  error: lock instance is no longer acquired
  ```

/

**Job 2**
 :arrow_up: Env
  ```
  acquiring lock on: aws-bosh-release
  .........................................................
  ```

  :arrow_down: Env
  ```
  Cloning into '/tmp/build/get'...
  70c75d1 claiming: mars
  ```

Commits in Git logs show that Job #2's claim happened immediately after Job #1 's unclaim.

**Comment by vito** [comment]
sweet emoji art

**Comment by jtarchie** [comment]
Reproducible steps:

## Setup

```sh
mkdir -p repo/pool/unclaimed
mkdir -p repo/pool/claimed
cd repo
git init
git add -A
git ci -m 'init pool of resources'
```

## Job A performing the `put` on a concourse pipeline

```sh
git mv pool/unclaimed/RESOURCE pool/claimed/RESOURCE
git ci -m 'claiming resource from Job A'

git mv pool/claimed/RESOURCE pool/unclaimed/RESOURCE
git ci -m 'unclaiming resource from Job A'
ref=$(git log HEAD --format="%H" | head -1)
```

## Job B claiming the resource

```sh
git mv pool/unclaimed/RESOURCE pool/claimed/RESOURCE
git ci -m 'claiming resource from Job B'
```

## Job A then running the `/opt/resource/in` script on it's ref

```sh
$ git log --oneline $ref..HEAD -- pool/
869df45 claiming resource from Job B
```

The following is showing the error message from [here](https://github.com/concourse/pool-resource/blob/0d49c16b632cf47d27a1c81e33702a8c30a8888f/assets/in#L17).

It looks like a possible solution may be just filtering out subsequent claimed messages.

For example.

```sh
$ git log --grep '^claiming' --invert-grep --oneline $ref..HEAD -- pool/
```

There is no output from this command.

**Comment by jtarchie** [comment]
We've tested the above fix on our concourse deployment and we no longer experience the error.
