### ISSUE TITLE
getting ressource fails with: fatal: ambiguous argument 'HEAD~1' 

### ISSUE THREAD

**Issue by c0d1ngm0nk3y** [concourse/pool-resource#55]
After updating concourse from 6.2 to 6.3, the pool resource fails on every get with

```bash
fatal: ambiguous argument 'HEAD~1': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
basename: missing operand
Try 'basename --help' for more information
```

This problem was introduced with the docker image concourse/pool-resource:1.1.2. Using concourse/pool-resource:1.1.1 instead works fine.

**Comment by c0d1ngm0nk3y** [comment]
Looks like a untested git version to me :(

**Comment by tlwr** [comment]
See also https://github.com/concourse/pool-resource/issues/54
