### ISSUE TITLE
Lack of support for "git_config"

### ISSUE THREAD

**Issue by ywei2017** [concourse/pool-resource#63]
Our git server recently enabled commit identity verification -- the user.email of the committer needs to be a verified user email.  With that, the pool resource will no longer work, due to [the hard coded user.email config](https://github.com/concourse/pool-resource/blob/master/out/git_lock_handler.go#L213).

This can be solved similar to how the "git_config" parameters does for the git resource type.

**Comment by xtremerui** [comment]
implemented in 6de7c7ad1b3439a72864153c6a86e3e026fb98dd
